---
on: push

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push docker images
      env:
        IMAGE_REGISTRY: docker.io
        REGISTRY_NAMESPACE: oussabe
      run: |
        branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        version="${branch#release-}"
        export IMAGE_TAG=$(date "+${version}-%Y-%m-%d-%H%M%S")
        export OCS_BUNDLE_IMG="docker.io/oussabe/ocs-operator-bundle:4.15-2024-04-30-115029"
        make docker-build docker-push
        make bundle-build bundle-push
        make catalog-build catalog-push
